server:
  port: 8081
  max-http-header-size: 10000000

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/crazyworld?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crazyphilip.terminal.entity

#showSql
logging:
  level:
    com:
      crazyphilip:
        terminal:
          mapper : debug